CREATE DATABASE weather_calendar;
USE weather_calendar;

<<<<<<< HEAD
-- CREATE TABLE `WEEKLY_FORECAST` (
--   `DATE` DATETIME NOT NULL,
--   `LOCATION` Int( 255) NOT NULL,
--   `TEMP` VARCHAR( 255 ) NOT NULL,
--   `ICON` Int NOT NULL,
=======
CREATE TABLE `Calendar` (
  `DATE` DATETIME NOT NULL,
  `LOCATION` Int( 255) NOT NULL,
  `TEMP` VARCHAR( 255 ) NOT NULL,
  `ICON` Int NOT NULL,
>>>>>>> 28fd1cd49ef7e900127f23012c2787d9f988ce88

--   PRIMARY KEY ( `DATE` ) 
-- );

<<<<<<< HEAD
-- CREATE TABLE `SUGGESTED_ACTIVITY` (
--   `ID` Int( 11 ) AUTO_INCREMENT NOT NULL,
--   `ACTIVITY` VARCHAR( 255) NOT NULL,
--   `ICON` Int ( 255 ) NOT NULL,
--   `THRESHOLD` DATETIME NOT NULL,
=======
CREATE TABLE `Activities` (
  `ID` Int( 11 ) AUTO_INCREMENT NOT NULL,
  `ACTIVITY` VARCHAR( 255) NOT NULL,
  `ICON` Int ( 255 ) NOT NULL,
  `THRESHOLD` DATETIME NOT NULL,
>>>>>>> 28fd1cd49ef7e900127f23012c2787d9f988ce88

--   PRIMARY KEY ( `ID` ) 
-- );

<<<<<<< HEAD
-- CREATE TABLE `PLANNED_ACTIVITY` (
--   `ID` Int( 11 ) AUTO_INCREMENT NOT NULL,
--   `DATE` DATETIME( 255) NOT NULL,
--   `SCHEDULE` VARCHAR( 255 ) NOT NULL
=======
CREATE TABLE `Post` (
  `ID` Int( 11 ) AUTO_INCREMENT NOT NULL,
  `DATE` DATETIME( 255) NOT NULL,
  `SCHEDULE` VARCHAR( 255 ) NOT NULL
>>>>>>> 28fd1cd49ef7e900127f23012c2787d9f988ce88

--   PRIMARY KEY ( `ID` ) 
-- );
