CREATE DATABASE weather_calendar;
USE weather_calendar;

CREATE TABLE `Calendar` (
  `DATE` DATETIME NOT NULL,
  `LOCATION` Int( 255) NOT NULL,
  `TEMP` VARCHAR( 255 ) NOT NULL,
  `ICON` Int NOT NULL,

  PRIMARY KEY ( `DATE` ) 
);

CREATE TABLE `Activities` (
  `ID` Int( 11 ) AUTO_INCREMENT NOT NULL,
  `ACTIVITY` VARCHAR( 255) NOT NULL,
  `ICON` Int ( 255 ) NOT NULL,
  `THRESHOLD` DATETIME NOT NULL,

  PRIMARY KEY ( `ID` ) 
);

CREATE TABLE `Post` (
  `ID` Int( 11 ) AUTO_INCREMENT NOT NULL,
  `DATE` DATETIME( 255) NOT NULL,
  `SCHEDULE` VARCHAR( 255 ) NOT NULL

  PRIMARY KEY ( `ID` ) 
);
